name: Build Skippi
on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Set up JDK 17
        uses: actions/setup-java@main
        with:
          java-version: 17
          distribution: temurin
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Upload Skippi
        uses: actions/upload-artifact@main
        with:
          name: PAPI-Expansion-Skippi
          path: target/*.jar
      - name: Release Skippi
        uses: marvinpinto/action-automatic-releases@master
        with:
          title: "Skippi v1.0.1"
          automatic_release_tag: "1.0.1"
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          files: "target/*.jar"
          prerelease: false